export const USER = {
  USER_NOT_FOUND: 'lang.AUTH.USER_NOT_FOUND',
  VALIDATE_MIN_LENGTH_EMAIL: 'lang.AUTH.VALIDATE_MIN_LENGTH_EMAIL',
  VALIDATE_MAX_LENGTH_EMAIL: 'lang.AUTH.VALIDATE_MAX_LENGTH_EMAIL',
  REQUIRE_FIELD_EMAIL: 'lang.AUTH.REQUIRE_FIELD_EMAIL',
  VALIDATE_MAX_LENGTH_PASSWORD: 'lang.AUTH.VALIDATE_MAX_LENGTH_PASSWORD',
  VALIDATE_MIN_LENGTH_PASSWORD: 'lang.AUTH.VALIDATE_MIN_LENGTH_PASSWORD',
  REQUIRE_FIELD_PASSWORD: 'lang.AUTH.REQUIRE_FIELD_PASSWORD',
  INVALID_PASSWORD: 'lang.AUTH.INVALID_PASSWORD',
  FIRST_NAME_NOT_EMPTY: 'lang.USER.FIRST_NAME_NOT_EMPTY',
  FIRST_NAME_MAX_LENGTH: 'lang.USER.FIRST_NAME_MAX_LENGTH',
  LAST_NAME_NOT_EMPTY: 'lang.USER.LAST_NAME_NOT_EMPTY',
  LAST_NAME_MAX_LENGTH: 'lang.USER.LAST_NAME_MAX_LENGTH',
  PASSWORD_NOT_EMPTY: 'lang.USER.PASSWORD_NOT_EMPTY',
  PASSWORD_MIN_LENGTH: 'lang.USER.PASSWORD_MIN_LENGTH',
  PASSWORD_MAX_LENGTH: 'lang.USER.PASSWORD_MAX_LENGTH',
  PASSWORD_FORMAT_INCORRECT: 'lang.USER.PASSWORD_FORMAT_INCORRECT',
  REGION_CODE_NOT_EMPTY: 'lang.USER.REGION_CODE_NOT_EMPTY',
  REGION_CODE_INCORRECT: 'lang.USER.REGION_CODE_INCORRECT',
  PHONE_NUMBER_NOT_EMPTY: 'lang.USER.PHONE_NUMBER_NOT_EMPTY',
  PHONE_NUMBER_MIN_LENGTH: 'lang.USER.PHONE_NUMBER_MIN_LENGTH',
  PHONE_NUMBER_MAX_LENGTH: 'lang.USER.PHONE_NUMBER_MAX_LENGTH',
  USER_IS_BLOCKED: 'lang.USER.USER_IS_BLOCKED',
  USER_IS_NOT_ACTIVE: 'lang.USER.USER_IS_NOT_ACTIVE',
  USER_IS_FROZEN: 'lang.USER.USER_IS_FROZEN',
  NOT_CREATE_OR_UPDATE_USER_STATUS_FROZEN: 'lang.USER.NOT_CREATE_OR_UPDATE_USER_STATUS_FROZEN'
};

export const COUNTRY = {
  COUNTRY_NOT_EMPTY: 'lang.COUNTRY.COUNTRY_NOT_EMPTY',
  COUNTRY_NOT_EXISTED: 'lang.COUNTRY.COUNTRY_NOT_EXISTED',
};