export const USER_VALIDATOR = {
    FIRST_NAME_MAX_LENGTH: 100,
    LAST_NAME_MAX_LENGTH: 100,
    EMAIL_MAX_LENGTH: 255,
    PHONE_NUMBER_MIN_LENGTH: 8,
    PHONE_NUMBER_MAX_LENGTH: 13,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 32
};